export const NodeType = {
  BinaryExpression: "BinaryExpression",
  BlockStatement: "BlockStatement",
  RelationalExpression: "RelationalExpression",
  EqualityExpression: "EqualityExpression",
  InitStatement: "InitStatement",
  EmptyStatement: "EmptyStatement",
  VariableDeclaration: "VariableDeclaration",
  NumericLiteral: "NumericLiteral",
  AssignmentExpression: "AssignmentExpression",
  ExpressionStatement: "ExpressionStatement",
  NullLiteral: "NullLiteral",
  IdentifierExpression: "IdentifierExpression",
  VariableStatement: "VariableStatement",
  StringLiteral: "StringLiteral",
  PrintStatement: "PrintStatement",
  IfStatement: "IfStatement",
  WhileStatement: "WhileStatement",
  BreakStatement: "BreakStatement",
  ContinueStatement: "ContinueStatement",
  BooleanLiteral: "BooleanLiteral",
  Program: "Program",
};
  